spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authority?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: secret
server:
  port: 8081