spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: secret
server:
  port: 8081